import type { DeepPartial, Localization } from "@better-auth-ui/core";

export const spanishLocalization = {
    auth: {
        // --- existing keys ---
        continueWith: "Continuar con {{provider}}",
        email: "Correo electrónico",
        emailPlaceholder: "correo@ejemplo.com",
        or: "o",
        signIn: "Bienvenido de vuelta",
        signOut: "Cerrar sesión",
        signUp: "Registrarse",
        // --- keys used by Auth / AuthCard surfaces ---
        account: "Cuenta",
        alreadyHaveAnAccount: "¿Ya tienes una cuenta?",
        confirmPassword: "Confirmar contraseña",
        confirmPasswordPlaceholder: "Confirma tu contraseña",
        fieldRequired: "Este campo es obligatorio",
        forgotPassword: "Recuperar contraseña",
        forgotPasswordLink: "¿Olvidaste tu contraseña?",
        hidePassword: "Ocultar contraseña",
        invalidEmail: "Por favor ingresa un correo electrónico válido",
        invalidResetPasswordToken:
            "Token de restablecimiento de contraseña no válido",
        name: "Nombre",
        namePlaceholder: "Ingresa tu nombre",
        needToCreateAnAccount: "¿Necesitas crear una cuenta?",
        newPassword: "Nueva contraseña",
        newPasswordPlaceholder: "Ingresa tu nueva contraseña",
        password: "Contraseña",
        passwordPlaceholder: "Ingresa tu contraseña",
        passwordResetEmailSent: "Correo de restablecimiento enviado",
        passwordResetSuccess: "Contraseña restablecida con éxito",
        passwordsDoNotMatch: "Las contraseñas no coinciden",
        rememberMe: "Recordarme",
        rememberYourPassword: "¿Recuerdas tu contraseña?",
        resend: "Reenviar",
        resetPassword: "Restablecer contraseña",
        sendResetLink: "Enviar enlace de restablecimiento",
        showPassword: "Mostrar contraseña",
        tooLong: "Máximo {{max}} caracteres",
        tooShort: "Mínimo {{min}} caracteres",
        verificationEmailSent: "¡Correo de verificación enviado!",
        verifyYourEmail: "Verifica tu correo electrónico",
    },
    settings: {
        // --- existing keys ---
        account: "Cuenta",
        saveChanges: "Guardar cambios",
        security: "Seguridad",
        // --- keys used by Settings surfaces ---
        accountUnlinked: "Cuenta desvinculada",
        active: "Activa",
        activeSessions: "Sesiones activas",
        avatar: "Avatar",
        avatarChangedSuccess: "Avatar actualizado correctamente",
        avatarDeletedSuccess: "Avatar eliminado correctamente",
        cancel: "Cancelar",
        changeAvatar: "Cambiar avatar",
        changeEmail: "Cambiar correo electrónico",
        changeEmailSuccess: "Revisa tu correo para confirmar el cambio",
        changePassword: "Cambiar contraseña",
        changePasswordSuccess: "Contraseña cambiada correctamente",
        copyToClipboard: "Copiar al portapapeles",
        currentPassword: "Contraseña actual",
        currentPasswordPlaceholder: "Ingresa tu contraseña actual",
        currentSession: "Sesión actual",
        dangerZone: "Zona de peligro",
        delete: "Eliminar",
        deleteAvatar: "Eliminar avatar",
        link: "Vincular",
        linkedAccounts: "Cuentas vinculadas",
        linkProvider: "Vincula tu cuenta de {{provider}}",
        optional: "Opcional",
        profileUpdatedSuccess: "Perfil actualizado correctamente",
        revoke: "Revocar",
        revokeSession: "Revocar sesión",
        revokeSessionSuccess: "Sesión revocada correctamente",
        setPassword: "Establecer contraseña",
        setPasswordDescription:
            "Aún no tienes contraseña. Solicita un enlace de restablecimiento para configurarla.",
        settings: "Configuración",
        time: "Tiempo",
        unlinkProvider: "Desvincular {{provider}}",
        updateEmail: "Actualizar correo electrónico",
        updatePassword: "Actualizar contraseña",
        uploadAvatar: "Subir avatar",
        userProfile: "Perfil de usuario",
    },
} satisfies DeepPartial<Localization>;
